library(tidyverse)
library(dataReporter)
library(here)
library(haven)

dataset_name <- "lut_2020"

metadata <- read_csv(here("0_metadata/metadata.csv")) %>% 
  filter(dataset == dataset_name)

file_type <- tools::file_ext(metadata$filename)

if (file_type == "sav") {
  data <- read_sav(here("1_data_raw", metadata$dataset, metadata$filename))
} else if (file_type == "dta") {
  data <- read_dta(here("1_data_raw", metadata$dataset, metadata$filename))
} else if (file_type == "csv") {
  data <- read_csv(here("1_data_raw", metadata$dataset, metadata$filename))
} else {
  stop("Add code for filetype: ", file_type)
}

makeCodebook(data, 
  file = here("1_data_raw", dataset_name, "codebook_autogenerated.Rmd"), 
  reportTitle = glue::glue("Codebook for {dataset_name}"), output = "html", codebook = TRUE)
